name: build
on:
  push:
    paths-ignore:
      - "**.md"
  # manual trigger
  workflow_dispatch: {}
env:
  RUST_BACKTRACE: "1"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: cargo build --workspace --features tokio
      - run: cargo fmt --check
      - run: cargo clippy
  test_linux:
    name: Test / Linux (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: stable
            features: --features tokio
          - toolchain: nightly
            features: --all-features
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build --workspace ${{ matrix.features }}
      - run: cargo test --verbose --workspace ${{ matrix.features }}