name: build
on:
  push:
    paths-ignore:
      - "**.md"
  # manual trigger
  workflow_dispatch: {}
env:
  RUST_BACKTRACE: "1"
jobs:
  test_linux:
    name: Test / Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1  # Uses rust-toolchain file
        with:
          components: rustfmt
      - run: cargo build
      - run: cargo fmt --check
      - run: cargo test --verbose
